---
  # Parameters:

  - name: PostgreSQL | Check if is installed
    command: test -x /usr/bin/psql
    register: psql_present
    ignore_errors: yes
    tags: psql

  - name: PostgreSQL | Add GPG key to apt keyring
    apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present
    when: psql_present|failed
    tags: psql
    become: yes

  - name: PostgreSQL | Add apt repository
    apt_repository: repo="deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main" state=present update_cache=yes
    tags: psql
    when: psql_present|failed
    become: yes

  - name: PostgreSQL | Install
    apt: update-cache=yes force=yes state=present pkg={{item}}
    with_items:
      - "postgresql-{{postgresql_version}}"
      - libpq-dev
      - python-psycopg2
    become: yes
    when: psql_present|failed
    tags: psql
