---

- name: "TeamCity | Stop service"
  become: yes
  become_user: root
  shell: '"{{ teamcity_install_dir }}/TeamCity/bin/teamcity-server.sh" stop'

- name: "Teamcity | Uninstall"
  become: yes
  become_user: root
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ teamcity_data_dir }}/TeamCity"
    - "{{ teamcity_data_dir }}/buildserver/lib/jdbc/"
  when: '"{{ teamcity_installed_version.stdout }}" != "{{ teamcity_version }}"'