---
- hosts: www

  vars:
    - root_dir: "{{playbook_dir}}/../"


  pre_tasks:
    - debug: msg="Pre tasks section"

  roles:
    - {
        role: "sa-teamcity"
      }


  tasks:
    - debug: msg="Tasks section"
